sudo: required
services:
  - docker

before_install:
  - docker build -t avismg22/dockerreact -f Dockerfile.dev .

script:
  - docker run avismg22/dockerreact npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "dockerreact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-614821314556"
  bucket_path: "dockerreact"
  on:
    branch: master
  access_key_id: $AWS_Access_key
  secret_access_key:
    secure: "$AWS_Secret_key"
